// src/components/Projects.vue
<template>
	<v-container style="width:100%">
		<v-layout>
			<v-flex mt-3 mb-5>
				<h1 class="display-1">プロジェクト</h1>
			</v-flex>
		</v-layout>

		<v-layout row mb-5>
			<!-- offset：offset-md1 offset-xl1) -->
			<v-flex xs4 sm4 md4 xl4 mr-5 ml-5>
				<v-img :src="require('../assets/projects/eh_phf.gif')" contain></v-img>
			</v-flex>
			<v-flex xs6 sm6 md6 xl6>
				<h2 class="headline font-weight-bold mb-1">投影バーチャルハンドインタフェースに対する疑似触覚フィードバックの応用</h2>
				<p class="subtitle-1 mb-3">(IEEE Access 2020, IEEE World Haptics 2019 Poster, Demo)</p>
				<p class="body-1">ユーザの手の動きに連動して動くバーチャルハンドをプロジェクタから投影する投影バーチャルハンドインタフェースは、日常生活でのユーザの手の届く範囲を拡張することができます。しかし、投影バーチャルハンドが実物体に重なった際、ユーザはその物体に触れている感覚を得られません。本プロジェクトでは、投影バーチャルハンドが実物体に触れた際に、バーチャルハンドに視覚効果を付与することで、疑似触覚フィードバックによりユーザにその物体の触感を知覚させる手法を提案しました。</p>
			</v-flex>
		</v-layout>

		<v-layout row mb-5>
			<v-flex xs4 sm4 md4 xl4 mr-5 ml-5>
				<v-img :src="require('../assets/projects/farfeel.jpg')" contain></v-img>
			</v-flex>
			<v-flex xs6 sm6 md6 xl6>
				<h2 class="headline font-weight-bold mb-1">fARFEEL: Providing Haptic Sensation of Touched Objects Using Visuo-Haptic Feedback</h2>
				<p class="subtitle-1 mb-3">(IEEE VR 2019 Demo)</p>
				<p class="body-1">
				We present fARFEEL, a remote communication system that provides visuo-haptic feedback allows a local user to feel touching distant objects. The system allows the local and remote users to communicate by using the projected virtual hand (VH) for the agency of his/her own hands. The necessary haptic information is provided to the non-manipulating hand of the local user that does not bother the manipulation of the projected VH. We also introduce the possible visual stimulus that could potentially provide the sense of the body ownership over the projected VH.
				</p>
			</v-flex>
		</v-layout>
	</v-container>
</template>


<style>
</style>

// src/app/projects/projects.component.ts
import { Component, OnInit, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'app-projects',
  templateUrl: './projects.component.html',
  styleUrls: ['./projects.component.css'],
  encapsulation: ViewEncapsulation.None, // needed to apply css to innerhtml
})

export class ProjectsComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="container">
	<div class="row mb-5">
		<div class="col">
			<h3 class="headline">Project / プロジェクト
				<hr />
			</h3>
		</div>
	</div>
</div>

<div class="container">
	<div id="project" class="project-body"></div>

	<div class='row mb-5'>
		<div class='col-md-5 mb-1'>
			<img src="images/projects/eh_phf.gif" class='project-image'>
		</div>
		<div class='col-md-7 mb-1'>
			<div class='project-title'>投影バーチャルハンドインタフェースに対する疑似触覚フィードバックの応用</div>
			<div class='project-publication'>(IEEE Access 2020, IEEE World Haptics 2019 Poster, Demo)</div>
			<div class='project-abstract mt-3'>
				ユーザの手の動きに連動して動くバーチャルハンドをプロジェクタから投影する投影バーチャルハンドインタフェースは、日常生活でのユーザの手の届く範囲を拡張することができます。しかし、投影バーチャルハンドが実物体に重なった際、ユーザはその物体に触れている感覚を得られません。本プロジェクトでは、投影バーチャルハンドが実物体に触れた際に、バーチャルハンドに視覚効果を付与することで、疑似触覚フィードバックによりユーザにその物体の触感を知覚させる手法を提案しました。
			</div>
		</div>
	</div>

	<div class='row mb-5'>
		<div class='col-md-5 mb-1'>
			<img src="images/projects/farfeel.jpg" class='project-image'>
		</div>
		<div class='col-md-7 mb-1'>
			<div class='project-title'>fARFEEL: Providing Haptic Sensation of Touched Objects Using Visuo-Haptic
				Feedback</div>
			<div class='project-publication'>(IEEE VR 2019 Demo)</div>
			<div class='project-abstract mt-3'>
				We present fARFEEL, a remote communication system that provides visuo-haptic feedback allows a local
				user to feel touching distant objects. The system allows the local and remote users to communicate by
				using the projected virtual hand (VH) for the agency of his/her own hands. The necessary haptic
				information is provided to the non-manipulating hand of the local user that does not bother the
				manipulation of the projected VH. We also introduce the possible visual stimulus that could potentially
				provide the sense of the body ownership over the projected VH.
			</div>
		</div>
	</div>

</div>

<div class="mb-5"></div>
