// src/app/others/cpp-tensorflow/cpp-tensorflow.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-cpp-tensorflow',
  templateUrl: './cpp-tensorflow.component.html',
  styleUrls: ['../others.component.css']
})
export class CppTensorflowComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="container">
  <div class="others-title-layout">
    <h6 class="others-title-date">2020-xx-xx　<i class="fas fa-sync-alt"></i> 2020-xx-xx
    </h6>
    <h1 class="others-title">
      c++から学習済みtensorflowモデルを呼び出す
      <hr />
    </h1>
    <h3 class="others-title-keywords">c++, tensorflow</h3>
    <h2 class="others-title-abstract">
      pythonで学習させたモデルをc++から利用したいよねっていう話です。tensorflowのc++ apiを上手くbuildできなかったので、c apiを使っています。(※GPUでは試せていません。CPU
      Onlyのお話です。)
    </h2>
  </div>


  <div class="others-body-layout">

    <div class="others-section">
      <h3 class="others-sec-title">
        現在、準備中です。
        <hr />
      </h3>

      <div class='others-body'>
        しばしお待ちください。
      </div>
    </div>
  </div>
</div>

// src/components/others_components/Cpp_Tensorflow.vue
<template>
	<v-container style="width:100%">
		<v-layout mt-3 mb-5>
			<v-layout>
			<h1 class="display-1">c++から学習済みtensorflowモデルを呼び出す</h1>
			</v-layout>
			<v-layout>
			<h2 class="body-1">Python&Tensorflowで学習させたモデルをc++アプリケーションに組み込んだお話です。(※GPUでは試せていません。CPU Onlyのお話です。)</h2>
			</v-layout>
		</v-layout>
	</v-container>
</template>


<style>
</style>
