// src/components/Home.vue
<template>

	<v-container style="width:90%">

		<!-- 文字後付け版
		<v-layout text-xs-center wrap class="home-hero__content" mb-5>
			<v-flex xs12 mt-5 mb-5>
				<h1 class="display-2 font-weight-bold mt-3 mb-3" style="color:#007641;">Welcome to Yushi's HP!</h1>
			</v-flex>
		</v-layout>
		-->
		
		<v-layout>
			<v-flex xs12 mt-5 mb-5>
				<v-img :src="require('../assets/images/home/home_photo.jpg')" contain width="100%"></v-img>
			</v-flex>
		</v-layout>
		

		<v-layout text-xs-left wrap ml-2 mb-5>	
			<v-flex>
				<h1 class="display-0 font-weight-bold mb-2">News</h1>
				<v-divider class="mb-3"></v-divider>
		
				<v-layout text-xs-left mb-2 ml-4 wrap>
					<v-flex xs12 sm5 md2 xl2>
						<p class="title font-weight-regular">
						2020.3.25
						</p>
					</v-flex>
					<v-flex ml-2>
						<p class="title font-weight-regular">
						<a class='news-link' href='https://www.iscie.or.jp/about/award' target='_blank'>システム制御情報学会</a>より2020年度学会賞「奨励賞」を受賞しました。
						</p>
					</v-flex>
				</v-layout>

				<v-layout text-xs-left mb-2 ml-4 wrap>
					<v-flex xs12 sm5 md2 xl2>
						<p class="title font-weight-regular">
						2019.8.24-9.7
						</p>
					</v-flex>
					<v-flex ml-2>
						<p class="title font-weight-regular">
						<a class='news-link' href='https://www.huawei.com/jp/sustainability/csr-news/hw_20190912' target='_blank'>HUAWEI Seeds for the Futureプログラム</a>に参加しました。
						</p>
					</v-flex>
				</v-layout>

				<v-layout text-xs-left mb-2 ml-4 wrap>
					<v-flex xs12 sm5 md2 xl2>
						<p class="title font-weight-regular">
						2019.5.24
						</p>
					</v-flex>
					<v-flex ml-2>
						<p class="title font-weight-regular">
						<a class='news-link' href='https://sci19.iscie.or.jp/award/' target='_blank'>第63回システム制御情報学会研究発表講演会</a>にて学生発表賞を受賞しました。
						</p>
					</v-flex>
				</v-layout>

				<v-layout text-xs-left mb-2 ml-4 wrap>
					<v-flex xs12 sm5 md2 xl2>
						<p class="title font-weight-regular">
						2019.4.1
						</p>
					</v-flex>
					<v-flex ml-2>
						<p class="title font-weight-regular">
						大阪大学大学院基礎工学研究科 博士前期課程に進学しました。
						</p>
					</v-flex>
				</v-layout>

				<v-layout text-xs-left mb-2 ml-4 wrap>
					<v-flex xs12 sm5 md2 xl2>
						<p class="title font-weight-regular">
						2019.3.3
						</p>
					</v-flex>
					<v-flex ml-2>
						<p class="title font-weight-regular">
						<a class='news-link' href='https://www.osaka-u.ac.jp/ja/news/topics/2019/03/1301' target='_blank'>第8回サイエンス・インカレ</a>にてファーウェイ賞を受賞しました。
						</p>
					</v-flex>
				</v-layout>
			</v-flex>
		</v-layout>

		<v-layout text-xs-left wrap ml-2 mb-4>	
			<v-flex>
				<h1 class="display-0 font-weight-bold mb-2">Links</h1>
				<v-divider class="mb-3"></v-divider>

				<p v-for="(eco, i) in link":key="i">
					<a v-bind:href=eco.href class="title font-weight-regular xs12 ml-4" target="_blank" style="color:#007641; text-decoration:none">
					<font-awesome-icon v-bind:icon=eco.icon color="#007641"/>
					{{eco.text}}</a>
				</p>
			</v-flex>
		</v-layout>



		<!-- 中心に寄せたい場合
		<v-layout text-xs-center wrap>	
			<h1 class="display-0 font-weight-bold mb-2">Links</h1>
			<v-divider class="mb-3"></v-divider>
		</v-layout>

		<v-layout text-xs-center wrap>	
			<v-flex v-for="(eco, i) in link":key="i">
				<a href=eco.href class="subheading mx-3" target="_blank">
				{{ eco.text }}</a>
			</v-flex>
		</v-layout>

		-->

			<!--
				<a 
						v-for="(eco, i) in link"
						:key="i"
						:href="eco.href"
						class="title font-weight-regular xs12 ml-4"
						target="_blank"
					>　{{ eco.text }}　</a>
			-->
	

				<!-- 真ん中に寄せる場合 
				<v-flex xs12 mb-5>
				<h2 class="display-1 font-weight-bold mb-3">Links</h2>

				<v-layout justify-center>
					<a
						v-for="(eco, i) in link"
						:key="i"
						:href="eco.href"
						class="subheading mx-3"
						target="_blank"
					>{{ eco.text }}</a>
				</v-layout>
				-->


			</v-flex>
			</v-flex>	
			</v-layout>
		</v-layout>
	</v-container>
</template>


<script lang="ts">
import { Vue, Component, Prop } from 'vue-property-decorator';
@Component
export default class Home extends Vue {
	private link = [
		{
			text: 'Github',
			icon: 'link',
			href: 'https://github.com/youseegreen',
		},
		{
			text: 'Google Scholar',
			icon: 'link',
			href: 'https://scholar.google.co.jp/citations?user=AO879_cAAAAJ',
		},
		{
			text: '研究室',
			icon: 'link',
			href: 'https://www.sens.sys.es.osaka-u.ac.jp/',
		},
		{
			text: '研究ページ',
			icon: 'link',
			href: 'https://www.extendedhand.net/',
		},
	];
}
</script>

<style>

.home-hero__content {
  background: url("../assets/images/home/home_photo.jpg");
  background-size: cover;
  background-position: center center;
  width: 100%;
  height: 70vh;
}
.news-link
{
  color: #007641;
  text-decoration: none;
}
</style>

// src/app/home/home.component.ts
import { Component, OnInit, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
  encapsulation: ViewEncapsulation.None, // needed to apply css to innerhtml
})
export class HomeComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="container mb-4">

  <!-- Image size should be 1300px * 540px -->
  <div id="home-photo" class="container">
    <img class="d-block w-100" src="images/home/home_photo.jpg" alt="home_photo">
  </div>
</div>


<div class="container">

  <div class="row">
    <div class="col">
      <h3 class="big-headline mt-3">News
        <hr />
      </h3>
    </div>
  </div>

  <div id="news" class="news-body ml-2">
    <div class='row mb-2'>
      <div class='col-md-2 pb-1'>2020.3.25</div>
      <div class='col-md-10'><a class='news-link' href='https://www.iscie.or.jp/about/award'
          target='_new'>システム制御情報学会</a>より2020年度学会賞「奨励賞」を受賞しました。</div>
    </div>
    <div class='row mb-2'>
      <div class='col-md-2 pb-1'>2019.8.24-9.7</div>
      <div class='col-md-10'><a class='news-link' href='https://www.huawei.com/jp/sustainability/csr-news/hw_20190912'
          target='_new'>HUAWEI Seeds for the Futureプログラム</a>に参加しました。</div>
    </div>
    <div class='row mb-2'>
      <div class='col-md-2 pb-1'>2020.3.25</div>
      <div class='col-md-10'><a class='news-link' href='https://sci19.iscie.or.jp/award/'
          target='_new'>第63回システム制御情報学会研究発表講演会</a>にて学生発表賞を受賞しました。</div>
    </div>
    <div class='row mb-2'>
      <div class='col-md-2 pb-1'>2019.4.1</div>
      <div class='col-md-10'>大阪大学大学院基礎工学研究科 博士前期課程に進学しました。</div>
    </div>
    <div class='row mb-2'>
      <div class='col-md-2 pb-1'>2020.3.25</div>
      <div class='col-md-10'><a class='news-link' href='https://www.osaka-u.ac.jp/ja/news/topics/2019/03/1301'
          target='_new'>第8回サイエンス・インカレ</a>にてファーウェイ賞を受賞しました。</div>
    </div>
  </div>

</div>



<div class="container">

  <div class="row">
    <div class="col">
      <h3 class="big-headline mt-4">Links
        <hr />
      </h3>
    </div>
  </div>

  <div id="link" class="news-body ml-1">
    <div class="row">
      <div class="col-10 my-2">
        <a href="https://github.com/youseegreen" target="_new">
          <span class="link-link ml-2"><i class='fas fa-link'></i> GitHub</span>
        </a>
      </div>
      <div class="col-10 my-2">
        <a href="https://scholar.google.co.jp/citations?user=AO879_cAAAAJ" target="_new">
          <span class="link-link ml-2"><i class='fas fa-link'></i> Googole Scholar</span>
        </a>
      </div>
      <div class="col-10 my-2">
        <a href="https://www.sens.sys.es.osaka-u.ac.jp/" target="_new">
          <span class="link-link ml-2"><i class='fas fa-link'></i> 研究室</span>
        </a>
      </div>
      <div class="col-10 my-2">
        <a href="https://www.extendedhand.net/" target="_new">
          <span class="link-link ml-2"><i class='fas fa-link'></i> 研究ページ</span>
        </a>
      </div>
    </div>
  </div>

</div>

<div class="mb-5"></div>
