// src/components/Publications.vue
<template>
  <v-container style="width:100%">
    <!--
	  <v-toolbar color=rgba(246,246,244) height=100px absolute flat>
		  <v-layout>
        <v-flex offset-md1 offset-xl1 ml-5>
		      <h1 class="display-1">発表業績</h1>
        </v-flex>
		  </v-layout>
		</v-toolbar>
    <v-card width=max-width outlined flat color=rgba(0,246,244,1) height=100px>
      <v-layout mb-5>
				<h1 class="display-1">発表業績</h1>
      </v-layout>
    </v-card>
    <v-layout mt-3 mb-5>
    <v-card flat color=rgba(0,246,244,1)>
				<h1 class="display-1">発表業績</h1>
    </v-card>
    </v-layout>
    -->

		<v-layout mt-3 mb-5>
			<v-flex>
				<h1 class="display-1">発表業績</h1>
			</v-flex>
		</v-layout>


    <!-- ページタイトルより右に持って行きたい場合、下の文を全てv-flex ml-xで囲めばよい -->
    <v-flex ml-3>
      <!-- 論文誌 -->    
      <v-flex xs12 mb-5>
      <h1 class="display-0 mb-2">論文誌</h1>
      <v-divider class="mb-3"></v-divider>
      <ol>
        <li class="headline mb-2 ml-3">
          <b>Yushi Sato</b>, Takefumi Hiraki, Naruki Tanabe, Haruka Matsukura, Daisuke Iwai, and Kosuke Sato, "Modifying Texture Perception with Pseudo-Haptic Feedback for a Projected Virtual Hand Interface," <i>IEEE Access</i>, Vol. 8, pp. 120473-120488, 2020.
        </li> 
      </ol>
      </v-flex>
    

      <!-- 国際会議 -->    
      <v-flex xs12 mb-5>
      <h1 class="display-0 mb-2">国際会議</h1>
      <v-divider class="mb-3"></v-divider>
      <ol>
        <li class="headline mb-2 ml-3">
          <b>Yushi Sato</b>, Naruki Tanabe, Kohei Morita, Takefumi Hiraki, Parinya Punpongsanon, Haruka Matsukura, Daisuke Iwai, and Kosuke Sato, "Pseudo-Haptic Feedback in a Projected Virtual Hand for Tactile Perception of Textures," In <i>Adjunct Proceedings of the 2019 IEEE World Haptics Conference (WHC 2019)</i>, pp.WP1P.09:1-2, July, 2019.
        </li> 
        <li class="headline mb-2 ml-3">
          <b>Yushi Sato</b>, Naruki Tanabe, Kohei Morita, Takefumi Hiraki, Parinya Punpongsanon, Haruka Matsukura, Daisuke Iwai, and Kosuke Sato, "Pseudo-Haptic Feedback in a Projected Virtual Hand for Tactile Perception of Textures," <i>The 2019 IEEE World Haptics Conference (WHC 2019)</i>, Hands-on Demos, DM2.09, July, 2019.
        </li> 
        <li class="headline mb-2 ml-3">
          Naruki Tanabe, <b>Yushi Sato</b>, Kohei Morita, Michiya Inagaki, Yuichi Fujino, Parinya Punpongsanon, Haruka Matsukura, Daisuke Iwai, and Kosuke Sato, "fARFEEL: Providing Haptic Sensation of Touched Objects using Visuo-Haptic Feedback," In <i>Proceedings of the 26th IEEE Conference on Virtual Reality and 3D User Interfaces (IEEE VR 2019)</i>, pp.1355-1356, March, 2019.
        </li> 
      </ol>
      </v-flex>

      <!-- 国内会議 -->    
      <v-flex xs12 mb-5>
      <h1 class="display-0 mb-2">国内会議</h1>
      <v-divider class="mb-3"></v-divider>
      <ol>
        <li class="headline mb-2 ml-3">
          <b>佐藤優志</b>，佐藤宏介，"投影型拡張手の実環境接触に対する視触覚フィードバック"，ヒューマンインタフェースサイバーコロキウム，2020年10月発表予定．
        </li>
        <li class="headline mb-2 ml-3">
          <b>佐藤優志</b>，平木剛史，松倉悠，岩井大輔，佐藤宏介，"投影型拡張手インタラクションに対する深層学習を用いた触覚フィードバック推定"，第25回日本バーチャルリアリティ学会大会，2020年9月発表予定．
        </li> 
        <li class="headline mb-2 ml-3">
          <b>佐藤優志</b>，平木剛史，田辺育暉，松倉悠，岩井大輔，佐藤宏介，"投影バーチャルハンドインタフェースへの疑似触覚の適用に関する一考察"，第60回複合現実感研究会(SIG-MR)，pp. MR2020-3:1-4, 2020年1月．
        </li> 
        <li class="headline mb-2 ml-3">
          <b>佐藤優志</b>，平木剛史，田辺育暉，松倉悠，岩井大輔，佐藤宏介，"投影手インタフェースの疑似触覚フィードバックによる材質感呈示手法"，質感のつどい第5回公開フォーラム（ポスター発表），2019年12月．
        </li> 
        <li class="headline mb-2 ml-3">
          <b>佐藤優志</b>，田辺育暉，森田耕平，プンポンサノン パリンヤ，松倉悠，岩井大輔，佐藤宏介，"投影バーチャルハンドにおける疑似触覚フィードバックによる接触感呈示"，第63回システム制御情報学会研究発表講演会講演論文集(SCI'19)，pp. 1367-1374，2019年5月．
        </li> 
        <li class="headline mb-2 ml-3">
          森田耕平，田辺育暉，<b>佐藤優志</b>，プンポンサノン パリンヤ，松倉悠，岩井大輔，佐藤宏介，"頭部方向を用いた投影型拡張仮想手の操作範囲の拡張"，第63回システム制御情報学会研究発表講演会講演論文集(SCI'19)，pp. 1375-1381，2019年5月．
        </li> 
        <li class="headline mb-2 ml-3">
          <b>佐藤優志</b>，"バーチャルハンドのPseudo-Haptic Feedbackによる材質感呈示手法"，第8回サイエンス・インカレ研究発表会要約集，発表番号47，p. 53，2019年3月．
        </li> 
        <li class="headline mb-2 ml-3">
          <b>佐藤優志</b>，西田茂生，"曲面多色像ホログラムの開発"，第24回精密工学会学生会員卒業研究発表講演会論文集(JSPE'17)，pp. 41-42，2017年3月．
        </li> 
      </ol>
      </v-flex>
    
      <!-- 受賞 -->    
      <v-flex xs12 mb-5>      
      <h1 class="display-0 mb-2">受賞</h1>
      <v-divider class="mb-3"></v-divider>
      <ol>
        <li class="headline mb-2 ml-3">
          2020年度学会賞「奨励賞」 (<b>佐藤優志</b>，田辺育暉，森田耕平，プンポンサノン パリンヤ，松倉悠，岩井大輔，佐藤宏介，"投影バーチャルハンドにおける疑似触覚フィードバックによる接触感呈示"，システム制御情報学会)，2020年3月受賞.
        </li> 
        <li class="headline mb-2 ml-3">
          SCI学生発表賞 (<b>佐藤優志</b>，田辺育暉，森田耕平，プンポンサノン パリンヤ，松倉悠，岩井大輔，佐藤宏介，"投影バーチャルハンドにおける疑似触覚フィードバックによる接触感呈示"，システム制御情報学会)，2019年5月受賞.
        </li> 
        <li class="headline mb-2 ml-3">
          ファーウェイ賞 (<b>佐藤優志</b>，"バーチャルハンドのPseudo-Haptic Feedbackによる材質感呈示手法"，第8回サイエンス・インカレ)，2019年3月受賞.
        </li> 
      </ol>
      </v-flex>

      <!-- その他・Web報道 -->    
      <v-flex xs12 mb-5>
      <h1 class="display-0 mb-2">その他・Web報道</h1>
      <v-divider class="mb-3"></v-divider>
      <ol>
        <li class="headline mb-2 ml-3">
          Seamless (<a href="https://shiropen.com/seamless/farfeel" style="word-break:break-all;" target="_blank">https://shiropen.com/seamless/farfeel</a>)
        </li> 
        <li class="headline mb-2 ml-3">
          MoguraVR (<a href="https://www.moguravr.com/world-haptics-conference-2019" style="word-break:break-all;" target="_blank">https://www.moguravr.com/world-haptics-conference-2019</a>)
        </li> 
      </ol>
      </v-flex>
    </v-layout>


    </v-flex>
	</v-container>
</template>

<style>

</style>

<!--
<script lang="ts"> 
import Publications from '../assets/data/publications/publications.json';

export default {
  name: 'Publications',
  data() {
    return {
			items: Publications,
    };
  },
};
-->
 
</script>

// src/app/publications/publications.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-publications',
  templateUrl: './publications.component.html',
  styleUrls: ['./publications.component.css']
})

export class PublicationsComponent implements OnInit {
  constructor() { }

  ngOnInit() {
  }
}

<div class="container">
  <div class="row mb-5">
    <div class="col">
      <h3 class="headline">Publication / 発表業績
        <hr />
      </h3>
    </div>
  </div>

  <div id="publication">

    <div class="row">
      <div class="col">
        <!--
        <h3 class="publications-title"><i class="fas fa-award"></i> Award / 受賞-->
        <h3 class="publications-title"><i class="fas fa-award"></i> 受賞
          <hr />
        </h3>
      </div>
    </div>

    <div id="award">
      <div class="publications-body">
        <ol>
          <li>インタラクティブ発表賞（PC推薦）（岡本祥宏，<b>佐藤優志</b>，岩井大輔，佐藤宏介，"イベントカメラを用いたレーザスペックル振動計測による遠隔触覚拡張"，情報処理学会インタラクション2023），2023年3月受賞.</li>
          <li>大阪大学大学院基礎工学研究科賞，2021年3月受賞.</li>
          <li>第17回IEEE関西支部学生研究奨励賞，2020年12月受賞.</li>
          <li>2020年度学会賞「奨励賞」 (<b>佐藤優志</b>，田辺育暉，森田耕平，プンポンサノン
            パリンヤ，松倉悠，岩井大輔，佐藤宏介，"投影バーチャルハンドにおける疑似触覚フィードバックによる接触感呈示"，システム制御情報学会)，2020年3月受賞.</li>
          <li>SCI学生発表賞 (<b>佐藤優志</b>，田辺育暉，森田耕平，プンポンサノン
            パリンヤ，松倉悠，岩井大輔，佐藤宏介，"投影バーチャルハンドにおける疑似触覚フィードバックによる接触感呈示"，システム制御情報学会)，2019年5月受賞.</li>
          <li>ファーウェイ賞 (<b>佐藤優志</b>，"バーチャルハンドのPseudo-Haptic Feedbackによる材質感呈示手法"，第8回サイエンス・インカレ)，2019年3月受賞.</li>
        </ol>
      </div>
    </div>


    <div class="row">
      <div class="col">
        <h3 class="publications-title mt-4"><i class="fas fa-book-open"></i> 論文誌
          <hr />
        </h3>
      </div>
    </div>

    <div id="journal">
      <div class="publications-body">
        <ol>
          <li><b>Yushi Sato</b>, Daisuke Iwai, and Kosuke Sato, "Responsive-ExtendedHand: Adaptive Visuo-Haptic Feedback Recognizing Object Property with RGB-D Camera for Projected Extended Hand," <i>IEEE Access</i>, Vol. 12, pp. 38247-38257, 2024. <a href="https://ieeexplore.ieee.org/document/10466568" target="_blank">[pdf<i class="fas fa-file-pdf"></i>]</a></li>
          <li><b>Yushi Sato</b>, Daisuke Iwai, and Kosuke Sato, "Sound Texture Feedback for a Projected Extended Hand Interface," <i>IEEE Access</i>, Vol. 12, pp. 27673-27682, 2024. <a href="https://ieeexplore.ieee.org/document/10440090" target="_blank">[pdf<i class="fas fa-file-pdf"></i>]</a></li>
          <li>岡本祥宏，<b>佐藤優志</b>，岩井大輔，佐藤宏介，"投影拡張手示指部にレーザスペックル振動計測機能を有する遠方触覚拡張"，日本バーチャルリアリティ学会論文誌，Vol. 28，No. 3，pp. 165-174，2023年．<a href="https://www.jstage.jst.go.jp/article/tvrsj/28/3/28_165/_article/-char/ja" target="_blank">[pdf<i class="fas fa-file-pdf"></i>]</a></li>
          <li>渡邊あきら，<b>佐藤優志</b>，内田琢也，岩井大輔，佐藤宏介，"レーザ走査プロジェクタによる輪郭投影手のミニマル表現と浮遊・接触感提示"，日本バーチャルリアリティ学会論文誌，Vol. 27，No. 2，pp. 152-162，2022年．<a href="https://www.jstage.jst.go.jp/article/tvrsj/27/2/27_152/_article/-char/ja/" target="_blank">[pdf<i class="fas fa-file-pdf"></i>]</a></li>
          <li><b>Yushi Sato</b>, Takefumi Hiraki, Naruki Tanabe, Haruka Matsukura, Daisuke Iwai, and Kosuke Sato, "Modifying Texture Perception with Pseudo-Haptic Feedback for a Projected Virtual Hand Interface," <i>IEEE Access</i>, Vol. 8, pp. 120473-120488, 2020. <a href="https://ieeexplore.ieee.org/document/9130660" target="_blank">[pdf<i class="fas fa-file-pdf"></i>]</a></li>
        </ol>
      </div>
    </div>


    <div class="row">
      <div class="col">
        <h3 class="publications-title mt-4"><i class="fas fa-chalkboard-teacher"></i> 国際会議
          <hr />
        </h3>
      </div>
    </div>

    <div id="international_conference">
      <div class="publications-body">
        <ol>
          <li><b>Yushi Sato</b>, Daisuke Iwai, and Kosuke Sato, "Shadow Effects for Representing Hovering-and-Contact States of a Projected Hand in Spatial Augmented Reality," In <i>Proceedings of the 32nd IEEE Conference on Virtual Reality and 3D User Interfaces Abstracts and Workshops (IEEE VRW 2025, VR-HSA)</i>, pp. xxx-xxx, Match, 2025. (in press)</li>
          <li>Shun Hanai, Yuto Takeuchi, <b>Yushi Sato</b>, Yoshihiro Okamoto, Daisuke Iwai, and Kosuke Sato, "Haptic Augmentation by a Wrist Mounted Device with Laser Speckle Vibration Sensing and Hand Projection," In <i>Proceedings of the 32nd IEEE Conference on Virtual Reality and 3D User Interfaces Abstracts and Workshops (IEEE VRW 2025, VR-HSA)</i>, pp. xxx-xxx, Match, 2025. (in press)</li>
          <li><b>Yushi Sato</b>, Daisuke Iwai, and Kosuke Sato, "Pseudo Tactile Feedback for Extended Hand Users," In <i>Proceedings of the 31st International Display Workshops (IDW 2024)</i>, pp. 920-922, December, 2024. (invited)</li>
          <li>Naoya Yoshimura, <b>Yushi Sato</b>, Yuta Kageyama, Jun Murao, Satoshi Yagi, and Parinya Punpongsanon, "Hugmon: Exploration of Affective Movements for Hug Interaction using Tensegrity Robot," In <i>Proceedings of the 2022 ACM/IEEE International Conference on Human-Robot Interaction (HRI 2022)</i>, pp. 1105-1109, March, 2022.</li>
          <li><b>Yushi Sato</b>, Naruki Tanabe, Kohei Morita, Takefumi Hiraki, Parinya Punpongsanon, Haruka Matsukura, Daisuke Iwai, and Kosuke Sato, "Pseudo-Haptic Feedback in a Projected Virtual Hand for Tactile Perception of Textures," In <i>Adjunct Proceedings of the 2019 IEEE World Haptics Conference (WHC 2019)</i>, pp.WP1P.09:1-2, July, 2019.</li>
          <li><b>Yushi Sato</b>, Naruki Tanabe, Kohei Morita, Takefumi Hiraki, Parinya Punpongsanon, Haruka Matsukura, Daisuke Iwai, and Kosuke Sato, "Pseudo-Haptic Feedback in a Projected Virtual Hand for Tactile Perception of Textures," <i>The 2019 IEEE World Haptics Conference (WHC 2019)</i>, Hands-on Demos, DM2.09, July, 2019.</li>
          <li>Naruki Tanabe, <b>Yushi Sato</b>, Kohei Morita, Michiya Inagaki, Yuichi Fujino, Parinya Punpongsanon, Haruka Matsukura, Daisuke Iwai, and Kosuke Sato, "fARFEEL: Providing Haptic Sensation of Touched Objects using Visuo-Haptic Feedback," In <i>Proceedings of the 26th IEEE Conference on Virtual Reality and 3D User Interfaces (IEEE VR 2019)</i>, pp.1355-1356, March, 2019.</li>
        </ol>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <h3 class="publications-title mt-4"><i class="fas fa-chalkboard-teacher"></i> 国内会議・研究会
          <hr />
        </h3>
      </div>
    </div>

    <div id="domestic_conference">
      <div class="publications-body">
        <ol>
          <li>中尾都史也，<b>佐藤優志</b>，岩井大輔，佐藤宏介，"制御可能な変形面へのプロジェクションマッピングによる動的立体表現"，第69回システム制御情報学会研究発表講演会，2025年5月発表予定．
          <li>高橋実，<b>佐藤優志</b>，岩井大輔，佐藤宏介，"投影型拡張手を用いた実物体操作感覚に関する研究"，第69回システム制御情報学会研究発表講演会，2025年5月発表予定．
          <li><b>佐藤優志</b>，石川蒼桜，岩井大輔，佐藤宏介，"投影型手腕拡張インタフェースの視聴覚効果による触感提示"，深奥質感シンポジウム（実演展示），2024年12月．</li>
          <li><b>佐藤優志</b>，石川蒼桜，竹内悠人，岩井大輔，佐藤宏介，"投影型手腕拡張インタフェースにおける視聴覚効果による浮遊・接触感提示"，第29回日本バーチャルリアリティ学会大会，pp. 2B2-06:1-3，2024年9月．</li>
          <li>石川蒼桜，<b>佐藤優志</b>，岩井大輔，佐藤宏介，"超指向性スピーカの反射音を用いた投影拡張手への音像提示"，第29回日本バーチャルリアリティ学会大会，pp. 2B1-09:1-2，2024年9月．</li>
          <li>花井俊，岡本祥宏，<b>佐藤優志</b>，岩井大輔，佐藤宏介，"手首装着型レーザスペックル振動計測を活用した触覚拡張による遠方物体の不可視情報識別"，第29回日本バーチャルリアリティ学会大会，pp. 1E1-07:1-4，2024年9月．</li>
          <li>石川蒼桜，<b>佐藤優志</b>，岩井大輔，佐藤宏介，"方向制御可能な超指向性スピーカを用いた投影拡張手への音像提示"，第68回システム制御情報学会研究発表講演会，pp. 967-970，2024年5月．
          <li>竹内悠人，<b>佐藤優志</b>，岩井大輔，佐藤宏介，"MEMSスキャナを用いた手首装着型拡張手投影システム"，第68回システム制御情報学会研究発表講演会，pp. 965-966，2024年5月．
          <li>竹内悠人，<b>佐藤優志</b>，岩井大輔，佐藤宏介，"エッジ深層学習を用いた手首装着型拡張手投影システム"，電子情報通信学会総合大会講演論文集，H-3-02，2024年3月．
          <li>人見亜斗，<b>佐藤優志</b>，岩井大輔，佐藤宏介，"表示情報遷移性のあるサイネージを用いた投影拡張手への感覚追加"，電子情報通信学会総合大会講演論文集，H-3-03，2024年3月．
          <li><b>佐藤優志</b>，内田琢也，岩井大輔，佐藤宏介，"CG手腕を受信映像に重畳し輪郭手腕を遠隔地へ同時投影するビデオ対話システム"，第67回システム制御情報学会研究発表講演会講演論文集(SCI'23)，pp. 335-337，2023年5月．
          <li>花井俊，内田琢也，<b>佐藤優志</b>，岩井大輔，佐藤宏介，"体動に頑健な肩装着小型拡張手投影システム"，第67回システム制御情報学会研究発表講演会講演論文集(SCI'23)，pp. 332-334，2023年5月．
          <li>岡本祥宏，<b>佐藤優志</b>，岩井大輔，佐藤宏介，"イベントカメラを用いたレーザスペックル振動計測による遠隔触覚拡張"，情報処理学会インタラクション2023論文集，pp. 857-859，2023年3月．<b>【プレミアム発表】</b></li>
          <li>内田琢也，<b>佐藤優志</b>，岩井大輔，佐藤宏介，"リストマウント型投影拡張手システムを用いた感覚追加"，情報処理学会インタラクション2023論文集，pp. 908-910，2023年3月．</li>
          <li><b>佐藤優志</b>，岩井大輔，佐藤宏介，"投影型手腕拡張インタフェースへの聴覚フィードバックの付与"，第27回日本バーチャルリアリティ学会大会，pp. 3D3-2:1-3，2022年9月．</li>
          <li>内田琢也，<b>佐藤優志</b>，岩井大輔，佐藤宏介，"投影型拡張手と実手との微小な運動不整合を手掛かりとする情報伝達"，第27回日本バーチャルリアリティ学会大会，pp. 1D2-5:1-3，2022年9月．</li>
          <li>人見亜斗，<b>佐藤優志</b>，内田琢也，岩井大輔，佐藤宏介，"マルチモーダル刺激環境における投影拡張手への感覚追加に関する研究"，第66回システム制御情報学会研究発表講演会講演論文集(SCI'22)，pp. 247-250，2022年5月．</li>
          <li><b>佐藤優志</b>，吉村直也，影山雄太，村尾淳，八木聡明，プンポンサノン パリンヤ，"テンセグリティ構造を有するハグ・インタラクション用ロボットの開発"，WISS 2021 (予稿なしデモポスター)，発表番号: 2-A09，2021年12月．</li>
          <li><b>佐藤優志</b>，岩井大輔，佐藤宏介，"投影型拡張手インタラクションにおける視覚効果付与に関する一考察"，第26回日本バーチャルリアリティ学会大会，pp. 2D2-1:1-4，2021年9月．</li>
          <li>渡邊あきら，内田琢也，<b>佐藤優志</b>，岩井大輔，佐藤宏介，"レーザ走査プロジェクタにおける拡張手の浮遊および接触表現"，第26回日本バーチャルリアリティ学会大会，pp. 3C2-3:1-3，2021年9月．</li>
          <li>内田琢也，渡邊あきら，<b>佐藤優志</b>，岩井大輔，佐藤宏介，"装着型拡張手システムを用いた不可知情報の可知化"，第26回日本バーチャルリアリティ学会大会，pp. 2D2-4:1-2，2021年9月．</li>
          <li>内田琢也，渡邊あきら，<b>佐藤優志</b>，岩井大輔，佐藤宏介，"レーザスキャン投影による装着型拡張手システム"，第65回システム制御情報学会研究発表講演会講演論文集(SCI'21)，pp. 392-394，2021年5月．</li>
          <li><b>佐藤優志</b>，佐藤宏介，"投影型拡張手の実環境接触に対する視触覚フィードバック"，ヒューマンインタフェースサイバーコロキウム論文集（HIC2），pp. 329-331，2020年10月．</li>
          <li><b>佐藤優志</b>，平木剛史，松倉悠，岩井大輔，佐藤宏介，"投影型拡張手インタラクションに対する深層学習を用いた触覚フィードバック推定"，第25回日本バーチャルリアリティ学会大会，pp. 3B2-1:1-3，2020年9月．</li>
          <li><b>佐藤優志</b>，平木剛史，田辺育暉，松倉悠，岩井大輔，佐藤宏介，"投影バーチャルハンドインタフェースへの疑似触覚の適用に関する一考察"，第60回複合現実感研究会(SIG-MR)，pp. MR2020-3:1-4, 2020年1月．</li>
          <li><b>佐藤優志</b>，平木剛史，田辺育暉，松倉悠，岩井大輔，佐藤宏介，"投影手インタフェースの疑似触覚フィードバックによる材質感呈示手法"，質感のつどい第5回公開フォーラム（ポスター発表），2019年12月．</li>
          <li><b>佐藤優志</b>，田辺育暉，森田耕平，プンポンサノン パリンヤ，松倉悠，岩井大輔，佐藤宏介，"投影バーチャルハンドにおける疑似触覚フィードバックによる接触感呈示"，第63回システム制御情報学会研究発表講演会講演論文集(SCI'19)，pp. 1367-1374，2019年5月．</li>
          <li>森田耕平，田辺育暉，<b>佐藤優志</b>，プンポンサノン パリンヤ，松倉悠，岩井大輔，佐藤宏介，"頭部方向を用いた投影型拡張仮想手の操作範囲の拡張"，第63回システム制御情報学会研究発表講演会講演論文集(SCI'19)，pp. 1375-1381，2019年5月．</li>
          <li><b>佐藤優志</b>，"バーチャルハンドのPseudo-Haptic Feedbackによる材質感呈示手法"，第8回サイエンス・インカレ研究発表会要約集，発表番号47，p. 53，2019年3月．</li>
          <li><b>佐藤優志</b>，西田茂生，"曲面多色像ホログラムの開発"，第24回精密工学会学生会員卒業研究発表講演会論文集(JSPE'17)，pp. 41-42，2017年3月．</li>
        </ol>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <h3 class="publications-title mt-4"><i class="fas fa-user-graduate"></i> 博士論文
          <hr />
        </h3>
      </div>
    </div>

    <div id="doctoral_dissertation">
      <div class="publications-body">
        <ol>
          <li><b>Yushi Sato</b>, "Pseudo Tactile Feedback for Extended Hand Users," 大阪大学大学院基礎工学研究科, 2024年9月. <a href="https://doi.org/10.18910/98682" target="_blank">[pdf<i class="fas fa-file-pdf"></i>]</a></li>
        </ol>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <h3 class="publications-title mt-4"><i class="fas fa-laptop"></i> その他・Web報道
          <hr />
        </h3>
      </div>
    </div>

    <div id="survey">
      <div class="publications-body">
        <ol>
          <li>Seamless (<a href="https://shiropen.com/seamless/farfeel" style="word-break:break-all;"
              target="_new">https://shiropen.com/seamless/farfeel</a>)</li>
          <li>MoguraVR (<a href="https://www.moguravr.com/world-haptics-conference-2019" style="word-break:break-all;"
              target="_new">https://www.moguravr.com/world-haptics-conference-2019</a>)</li>
        </ol>
      </div>
    </div>

  </div>
</div>

<div class="mb-5"></div>
